#!/bin/bash
# scripts/05-deploy.sh
#
# Phase 5 — Final deployment.
# Generates secrets, issues a self-signed TLS certificate, and starts the
# Docker Compose stack. Idempotent: safe to re-run.

set -euo pipefail

COMPOSE_DIR="${COMPOSE_DIR:-$(pwd)}"
ENV_FILE="$COMPOSE_DIR/.env"
CERT_DIR="$COMPOSE_DIR/certs"

# -----------------------------------------------------------------
# 1. Pre-flight
# -----------------------------------------------------------------
if [[ ! -f "$COMPOSE_DIR/docker-compose.yml" ]]; then
  echo "ERROR: docker-compose.yml not found in $COMPOSE_DIR."
  echo "       Run this script from the repository root."
  exit 1
fi

# -----------------------------------------------------------------
# 2. Generate .env if missing
# -----------------------------------------------------------------
if [[ ! -f "$ENV_FILE" ]]; then
  echo "==> [1/3] Generating .env with random secrets"
  PG_PASSWORD=$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)
  REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-32)
  WEBUI_SECRET=$(openssl rand -hex 32)

  cat > "$ENV_FILE" <<EOF
# Generated by 05-deploy.sh on $(date -Iseconds)
PG_PASSWORD=${PG_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
WEBUI_SECRET=${WEBUI_SECRET}
WEBUI_NAME=Enterprise AI Assistant
EOF
  chmod 600 "$ENV_FILE"
  echo "    Secrets written to $ENV_FILE (chmod 600)."
else
  echo "==> [1/3] Reusing existing .env"
fi

# -----------------------------------------------------------------
# 3. Generate self-signed TLS cert if missing
# -----------------------------------------------------------------
mkdir -p "$CERT_DIR"

if [[ ! -f "$CERT_DIR/server.crt" || ! -f "$CERT_DIR/server.key" ]]; then
  echo "==> [2/3] Generating 10-year self-signed TLS certificate"

  # Try to detect the primary IPv4 address; fall back to localhost.
  HOST_IP=$(ip -4 addr show 2>/dev/null \
    | awk '/inet / && $2 !~ /^127/ {print $2}' \
    | cut -d/ -f1 \
    | head -1 || echo "127.0.0.1")
  HOSTNAME_FQDN=$(hostname -f 2>/dev/null || hostname)

  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "$CERT_DIR/server.key" \
    -out "$CERT_DIR/server.crt" \
    -subj "/CN=${HOSTNAME_FQDN}" \
    -addext "subjectAltName=DNS:${HOSTNAME_FQDN},DNS:$(hostname),IP:${HOST_IP}"

  chmod 644 "$CERT_DIR/server.crt"
  chmod 600 "$CERT_DIR/server.key"
  echo "    Certificate issued for ${HOSTNAME_FQDN} / ${HOST_IP}"
  echo "    Replace with an internal-CA-signed cert before production."
else
  echo "==> [2/3] Reusing existing TLS certificate"
fi

# -----------------------------------------------------------------
# 4. Bring up the stack
# -----------------------------------------------------------------
echo "==> [3/3] Starting Docker Compose stack"
cd "$COMPOSE_DIR"
docker compose up -d

cat <<'EOM'

==============================================================================
Stack is starting.

vLLM cold-start typically takes 30–90 seconds depending on storage tier.
Watch progress with:

  docker compose logs -f vllm

The stack is ready when the log line "Uvicorn running on http://0.0.0.0:8000"
appears.

Then browse to https://<host-ip>/ and complete first-admin setup.
==============================================================================
EOM

echo
echo "Current container status:"
docker compose ps
